### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by nschejtman** [dropbox/mypy-PyCharm-plugin#12]
When loading the **mypy-plugin.jar** I get the following error:
> Fail to load plugin descriptor from file mypy-plugin.jar

**My Specs**
PyCharm 2018.1.4 (Professional Edition)
Build #PY-181.5087.37, built on May 24, 2018
JRE: 1.8.0_152-release-1136-b39 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.5

**Comment by ilevkivskyi** [comment]
Sorry for this! Could you please tell more about how do you (try to) install the plugin? I can't reproduce this, since I have an older PyCharm build.

**Comment by nschejtman** [comment]
@ilevkivskyi Yes. I go to Preferences -> Plugins -> Install plugin from disk... and select the _mypy-plugin.jar_ I've downloaded from the [link](https://github.com/dropbox/mypy-PyCharm-plugin/blob/master/mypy-plugin/mypy-plugin.jar) in the Readme.

**Comment by lightway82** [comment]
ubuntu 16.04
PyCharm 2018.1.4

**Comment by Lameorc** [comment]
I've encountered the same issue. I'm on PyCharm 2018.1 and Ubuntu 16 as well. As silly as this sounds I've been able to install it if I downloaded using the download button inside the github preview. If I've downloaded the file from the link in README, I get the above mentioned error.

Seems that if you download directly from the description, you get a HTML document instead of proper jar (even thought the filename suggests otherwise).

**Comment by nschejtman** [comment]
@Lameorc hahahaha that actually worked!

**Comment by lightway82** [comment]
Very strange

**Comment by ilevkivskyi** [comment]
Oh, I am so sorry. Somehow it worked for me. I will update the link in the description later today.

**Comment by ilevkivskyi** [comment]
OK, I updated the link in `README`, could you please double check that it works correctly?

**Comment by nschejtman** [comment]
@ilevkivskyi yes! Works fine now
